[build]
  command = "npm install && npm run build"
  publish = "build/"
  functions = "functions/"
    environment = { NODE_VERSION = "16.3.0" }

[[plugins]]
package = "@netlify/plugin-functions-install-core"