<script>
    import PlainSubscribe from "/src/lib/PlainSubscribe.svelte";
    import ShareButton from "/src/lib/ShareButton.svelte";
    import TopMatter from "/src/lib/TopMatter.svelte";  
    
    let title = "People's Green New Deal Summary";
    let description = "A primer of Max Ajl's book on ecosocialism, degrowth, and policy and social transitions";
    let og_image = "pgnd-cover.jpeg";
    let local_url = "peoples-green-new-deal-summary-max-ajl"
    let domain = "https://sambutler.us"
    let full_url = {domain} + "/" + {local_url};
  </script>

  <style>
    h4 > span {
      font-weight: normal;
    }

    /* h4 {
      display: inline;
    } */

    h4 + p {
      display: inline;
    }

    /* previous:has(+ p){
      display: inline;
    } */

  </style>
  
  <TopMatter title={title} description={description} og_image={og_image} full_url={full_url} local_url={local_url} domain={domain}></TopMatter>
  <article class="h-entry">
    <h1 class="p-name"><a class="u-url" href={local_url}>{title}</a></h1>
    <!-- <p style="font-style: italic">Sam Butler (February 2ndth, 2022 at 11:45am CEST)</p> -->
    <div class="e-content">
          
          <div><p><em>The following material is from the last chapters of Max Ajl's </em><a href="https://library.oapen.org/handle/20.500.12657/48775">"A People's Green New Deal"</a><em> —&nbsp;a blend of summary, edits, and remixes</em><em>.  It describes a framework of change relevant to confronting the climate crisis and imperialism. In contrast to the vague political and corporate climate plans of today, Ajl's "A People's Green New Deal" gets specific —&nbsp;and beautiful.</em></p>

            <a href="https://library.oapen.org/handle/20.500.12657/48775"><img src="/pgnd-cover.jpeg" style="margin: auto; max-width: 200px; display: block;"></a>
            <p><em>"A People's Green New Deal" </em><a href="https://library.oapen.org/handle/20.500.12657/48775">is available open access and free to download</a>, and a highly recommended read ...</p>
            
            <br>
            <span class="text-gray-500 text-sm" style="width: max-content; font-size: 14px; color: gray; text-align: center; display: block; margin: auto;">Recieve future content like this
                <svg xmlns="http://www.w3.org/2000/svg" style="vertical-align: bottom;" class="icon icon-tabler icon-tabler-mail" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="gray" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <rect x="3" y="5" width="18" height="14" rx="2" />
                <polyline points="3 7 12 13 21 7" />
              </svg></span>
                  <PlainSubscribe></PlainSubscribe>
              <br>

            <h3><em>We are ready for a more radical message.</em></h3>
            
            <p>Ready to demand sovereignty for the Third and Fourth Worlds &mdash; and struggle to secure that respect in the First World.</p>
            <p>Understand how this world was created and made unjust.&nbsp; Unequal economic exchange, resource use, and economic-environmental histories.&nbsp;</p>
            <p>Center the plans of <a href="https://pwccc.wordpress.com/2010/04/24/peoples-agreement/">the most oppressed, excluded, and harmed by our current system</a>.</p>
            <p>End interventions in the affairs of other nations, as a starting point for world-wide environmental revolution. The US, EU, and UK no longer deciding who rules other countries. Fighting for other countries' rights to determine their own paths.&nbsp; Ending intervention, demanding respect for international law, and dismantling militaries in the economic core.</p>
            <p>Recognize that the rich &mdash;&nbsp;whether countries, people, or corporations &mdash; are only rich by keeping the poor poor, through colonization, coups, war, and unequal exchange.</p>
            <p>Pay the climate debts that northern countries owe to southern countries &mdash; between $112 and $450 trillion dollars, or more&hellip;.</p>
            <p><strong>LandBack as the fast route to safeguarding the future.</strong>  Restoring treaty rights and decolonizing continents. Struggle from us in settler colonial states, to demand our governments restore land and treaty rights. Rights to access and use the environment, intertwined with rights to land and LandBack.</p>
            <p>LandBack as a shift which makes the world big enough for all of us.</p>
            <p><strong>National sovereignty,</strong> and the right for people to determine their own histories throughout the Third and Fourth worlds &mdash; and in the Third and Fourth worlds within settler colonial states.</p>
            <p>Sovereignty that allows Third World countries to redistribute land and lock in surplus locally &mdash; and cease using their own lands for exports.</p>
            <p>In the North, in the short-to-medium term, convergence among diverse groups (including national politics and the two-party system) around elements of a shared program. "Build and fight, fight and build", in the words of Cooperation Jackson, and dual power &mdash;&nbsp;building power in the current system, as we build the new.&nbsp; Fights for decreasing caps on fossil fuel use. For ecological debt repayments and for Third World sovereignty and technology transfers.&nbsp; These issues are inseparable, for they ensure that the right to the good life is shared on a planetary level.</p>
            <p>As the to-and-fro of struggle from municipal to international scale escalates, from the watershed to the continental shelf and beyond, quotas of fossil fuel use shrink.&nbsp; Paths once based on dumping waste into the shared sky &mdash; through agriculture, technology, planning, or engineering &mdash; are remade, through collective democratic decisions happening locally in metropolitan cores.</p>
            <p>Advancing the struggle for liberation in many colors and shades. Building with, rather than ignoring, the needs of the South.</p>
            <p><strong>... A demilitarized,</strong> peacetime economy.</p>
            <p>Converting existing military-industrial bases into factories that export renewable energy and technology. Helping other nations and peoples shift to cleaner forms of production without seeking profit &mdash; and transferring technology and reparation payments to help them do so.</p>
            <p>Universal access and local control of renewable energy, wherever possible. Full and equal access to electricity and 24 hour public libraries. Funding for the arts. Democratic, massive expansion of free high speed Internet. Moving people with public transport, bicycles, and local work. Food sovereignty. Fighting for climate reparations and climate debt payments to the south. Erasing economic apartheid between the First and Third worlds.</p>
            <p>The things we need we automatically get from living in a community, and doing these things in ways that do not damage the non-human environment.</p>
            <p>Agroecology and agriculture at the center. Food, and food cultures, at the nexus of life on Earth.</p>
            <p>Food sovereignty &mdash; communities in control of water, seed, and land.</p>
            <p>Agrarian reform, based on LandBack and decolonization of the settler land base.&nbsp; Land to the tiller reform, redistributed to workers and farmers.</p>
            <p>The priority of humanity: sewing carbon dioxide into the Earth, through food sovereignty and agroecology.</p>
            <p><strong>... Yards of </strong>pecan, chestnut, and breadfruit trees.</p>
            <p>Raspberry bushes and pomegranates, wrapped in grape vines and squash &mdash; lifting out from rich obsidian soil, filled with fresh tomatoes and peppers.</p>
            <p>Sideyards of fishponds, and manure from people and animals fattening up the fish. Roofs of patterned, raised garden beds &mdash; the rediscovery of old practices.</p>
            <p>Transformed grasslands, everywhere, roamed by native breed animals &mdash; grazing over forest fields, producing walnut, fodder, maize, and wheat, husbanded and stewarded by local ranchers.</p>
            <p>The relocalization of agriculture and urban farming. Parks &mdash; as many as possible. Gardens instead of lawns, over every inch of city. Green roofs. Streets lined with trees. Urban planning nested into surrounding ecologies. Agroforestry taking place of lawns, ornamental landscapes, rooftops, backyards, and golf courses. Patchworks of agroecology intercut with agroforestry, and patches of non-farmed land where communities can bloom. Urban places, threaded with wildlife places, in a forest of green.</p>
            <p>Urban mushroom gardens processing urban waste.</p>
            <p>Agrarian municipalism.</p>
            <p>Food coming from local food sheds, mapping over local watersheds, forming an ecological basis for a bioregional vision &hellip;</p>
            <p><strong>... The re-engineering </strong>of cities, in ways that do not erase that which makes them cities &mdash; their density. Taking an eraser and soft grey pencil to the hard black and white lines which separate the human-engineered concrete-stone-metal of the city, from the bucolic or even human-free natural realm of the wild or the countryside &hellip;</p>
            <p>Renewed urban planning, built on increased public access to living spaces within cities: parks as public affluence, macadamia and pear trees everywhere possible &mdash; supplying shade, regulating temperature in summer and winter, absorbing flood water, and converting CO2 to wood, bark, leaves, and roots.&nbsp;</p>
            <p>Reworked drainage systems, channeling water towards plantings and permeable pavements &mdash; labor-intensive projects, that smoothly enfold cities into ecological cycles. In the arid zones, models like Tunisia's Jerba, where cisterns lie under houses and the architecture channels rainwater to them.&nbsp; Rather than running off in inundated sewer systems, water collects for home use and irrigation. In a warming world, where oscillations between torrential downpours and droughts are ever more likely, technology &mdash; including housing and architecture &mdash; offer smooth and supple adaptations, through graceful, low-tech solutions.</p>
            <p>Alongside increased support for local agriculture and state compensation for carbon drawdown, a revitalized countryside with useful and non-alienated work to do.</p>
            <p>Countrysides peppered with cultural and infrastructural projects, from effective mass public transit, to high-speed internet, to health clinics. Free housing, single-unit and communal, built disproportionately in smaller rather than larger cities, using local materials. The small US towns, hamlets, villages, and exurbs, which are today ground zero for murderous white opioid epidemics and diseases of despair &mdash; are the basis for productive renaissances. Poorer Black populations, many scattered in smaller metropolises nationwide, benefit from reparations payments in the form of state-built housing &mdash; the state paying the cost of houses, that people design and commission themselves.</p>
            <p>The ongoing enchantment with community gardens building, as people get more involved in certain kinds of manual labor, hands touching dirt and grass and trees, more so than they do today. And cities pulsing, growing and shrinking based on patterns of state planning &mdash; unlike the new and static patterns of suburbs and exurbs.</p>
            <p>All of us, with the dignity to produce something of value and to be something.</p>
            <p>And plenty of things to do beyond farming and touching dirt.</p>
            <p><strong>Skilled technicians </strong>in the countryside and smaller towns and villages, managing high-voltage smart grids, local renewable storage systems, decentralized windmills. Artisans and decentralized workers processing local agricultural materials, supplementing and replacing mass-market industrial goods where it makes sense. Doctors, nurses, and students sourced from local populations, providing healthcare through countryside health clinics and training.</p>
            <p>The localization of production, health, food, the things we want, so we don't need to extract materials or workers or labor from other places &mdash; allowing us to respect other places' sovereignty, giving them space to determine their own histories, and to start determining our own histories locally.&nbsp; Ending the exploitation of other nations and unequal exchange, and ending the colonization and coups and wars in the process.</p>
            <p><strong>... New construction, </strong>built using local materials, which grow from with the variety of environments where people live.</p>
            <p>The <em>how</em>, <em>who</em>, and <em>where</em> of construction becoming an intersection of red labor and green holistic ecological planning &mdash; increasing people's power, stopping local exploitation, and breaking international chains of environmentally uneven exchange.</p>
            <p>By linking material production to local materials use, <em>construction, homes, industry, maintenance, production, manufacturing, services</em> &mdash; <em>everything we want and need</em> &mdash; are woven into the <strong>landscape management strategy</strong>, through local ecological stewardship and towards global carbon dioxide sequestration.</p>
            <p>Well-paid workers husband and cull local materials from natural processes &mdash; like bamboo and wood, which are harvested and regrow in the same place, leading to net negative carbon emissions, but also requiring the active management of the lands where those materials come from.&nbsp;</p>
            <p>Municipal, state, and federal/governmental mandates to use local materials promote decentralized human populations like this, and support those who need to husband the land from where the materials come, along with those who need to extract them, and those who need to manage the lands in perpetuity, to replace existing housing stock and infrastructure as materials wear out.&nbsp;</p>
            <p>This way, the lifecycles of our communities and our infrastructures, our products and services, our homes and homebuilding, are woven into our landscape management strategy &mdash; deciding what we grow and why, towards the satisfaction of local needs, and sewing carbon dioxide into the Earth.</p>
            <p>Retrofitting <em>existing</em> buildings for passive solar heating, improved insulation, and other energy-reducing and energy-eliminating features. Building <em>with</em> rather than against nature. This means retrofitting in the US, and new and old ways of thinking about architecture and design in the Third World. Living natural roofs and facades, which meld the urban with the natural landscape, and sharply decrease cooling costs.</p>
            <p>These vernacular building and retrofitting practices become decentralized, encouraged by state-level planning.</p>
            <p>This looks like localized, if not self-reliant, economies at much smaller scales, with interwoven sectors &mdash; and a decentralized distribution of extremely skilled labor.&nbsp;</p>
            <p>Foresters, harvesters, home builders. Husbandry, stewardship. Resurgences, like the revival of wood as massive timber &mdash; by clumping together chunks of softwoods like pine and spruce and birch and beech, creating larger blocks that can replace concrete and steel in building construction. Along with biochar in clay plasters, hemp building blocks, and straw bale buildings, these are our selection of carbon negative options.</p>
            <p>Homes and public buildings becoming artworks, made by local artisans, opening our doors to more local and circular economies. Walking through one door bringing us to another: returning to aspects of the past, but towards very different futures. Masonry, carpentry, iron-working, glass blowing, ceramic-working, weaving, all the necessary skills for artisanal-style home construction and decoration, resting on the transformation of local or agriculturally produced materials.&nbsp;</p>
            <p>This very best work and craftsmanship in the economic reach of poor people, and this very best work and craftsmanship in the homes where poor people can live.</p>
            <p>Every craftsman becoming an artist, every home-dweller becoming an art patron.&nbsp; Homes and living spaces which are extremely durable &mdash; and based on natural materials, incurring net-negative CO2 emissions in their production. Communal low-tech luxury. Some industrial processes which produce CO2 may endure, though our carbon sinks will outpace those carbon sources.</p>
            <p>Decentralized manufacturing hubs and fabrication labs, allowing the sharing of knowledge and tools to decentralize production, based on access to local materials, and reinforcing the importance of husbandry and local land management.&nbsp; Like the bamboo box, which allows us to mill and fabricate locally sourced bamboo into things we want and need.</p>
            <p>Shifts from industrialization and the transformations of abiotic, dead materials &mdash;&nbsp;like steel &mdash; towards <em>manufacturing, </em>and working with living material like wood and cotton. Attention to long-term projects, in the words of Colin Duncan, which make our lives cheaper now and later &mdash; like the slowly growing oak forests around the rim of Lake Ontario, allowing the city to phase out steel furniture in its universities and schools, replacing them with locally sourced and manufactured wood furniture and significantly less energy costs.&nbsp; Planning projects like this today.</p>
            <p>Bans on planned obsolescence, and shifts to planned longevity, as a collectively imposed standard for manufacturing &mdash; alongside easy capacity to repair all kinds of products.</p>
            <p>Countryside healthclinics, based on soft-footed, preventative, and knowledge-based forms of medicine &mdash; lowering the environmental impact of the hospital-industrial complex, and broadening access to life improving health for all peoples in all places.</p>
            <p><strong>... A shift in the temporal and organizational logic of industrial manufacturing</strong> &mdash; where questions of energy use, labor, manufacturing, and industrialization come together. Rethinking current patterns of production and the assumption of a constantly available energy, and recognizing a more supple approach to manufacturing, to solve a large portion of the renewable intermittency question.</p>
            <p>Processes that rely on mechanical energy &mdash; polishing, milling, hammering, crushing, sawing, cutting, turning &mdash; running on intermittent power.&nbsp; Food production, with intermittent olive pressing and grain grinding.&nbsp; The crushing of rock and ore, and textile work, like preparing fibers and weaving and knitting.&nbsp; All of this, running on intermittent energy when it is available.&nbsp; Industry and manufacturing grooving into the patterns of non-fossil fuel energy sources. Factories on a mix of wind and solar. Producing items in moments and seasons of abundant energy, and storing them close to consumers, for sale during low energy periods &mdash; turning clothing and furniture and cotton and food preserves into a different kind of energy storage &hellip;</p>
            <p>Cargo transport for most goods occurring with available renewable sources, whether wind or solar.&nbsp; Like Swedish plans for a wind-powered cargo ship, which can traverse the Atlantic in twelve days (only twice as long as current fossil fuel-powered journeys). Long-distance shipping undertaken more consciously, with wind, solar, and skysails. Transportation, shipping, and freight that moves when the wind blows and the sun shines &mdash; and planning our economies and lives around this accordingly.</p>
            <p><strong>Intra-urban transportation</strong> occurring on bicycles, e-bikes, and mass transit &mdash;&nbsp;from trolleys to trains, whererever possible. Private cars reserved for ambulances and emergency transport &ndash; times and places where society collectively decides the fruits of inherently damaging industrial production are worth protecting and convenience-ing human life. Re-routing and restricting cars from urban cores via congestion pricing and banning automobile entry.&nbsp; Convivial planning, in which work is centered closer to people's homes &mdash; understanding commuting distance as a primary indicator for our happiness at work. People having the ability to work within their neighborhoods, outside of extremely specialized fields like physics professors, historians, and archivists, who may work necessarily at specialized institutions. Understanding planning and transport as intermingled.</p>
            <p>Planning and urban landscapes contoured for minimum-energy and minimum-time commutes. Swapping walking and cycling in place of short car trips, cutting US domestic consumption up to 35 percent and making people healthier.&nbsp; Urban planning as a public health measure, reducing healthcare costs along the way.</p>
            <p><strong>Massive investment</strong> in the North and South in easily electrified forms of public transports:</p>
            <p>Buses, trams, trolleys, monorails, and subways within cities. National and international railroads between cities and between countries, alongside tremendous investments in high-speed rail. Transport becoming decommodified locally, paid for via wealth and real estate taxes, set fairly low, so the wealthiest pay the costs of universal access to transit. Longer-distance travel similarly decommodified with rationing &ndash; as it currently is, by the market. Investments in dirigibles and solar sails and other tools that replace flying with zero-carbon aerial and oceanic transport, all decommodified and freely accessible to people by virtue of birthright, and managed democratically at the smallest possible scale. Aviation scaled down while protecting jobs, and ensuring a just transition for all workers in the industry.</p>
            <p>^ This transition becoming easier, with healthcare, food, and housing as social rights &hellip;</p>
            <p><strong>Manufacturing and construction work</strong> paid a high wage, giving more people interest in the work, and circulating more value locally &mdash; creating wider local internal markets, and ever more useful carbon-negative work locally. Paying those who do the caretaking and teaching and child rearing at the same rates of other skilled labor, further enhancing the power of labor against capital, and the power of carbon-free work against carbon-intensive work.</p>
            <p>Mandatory workweeek caps of 20 hours or less, and massive increases &mdash;&nbsp;quintupling or more &mdash;&nbsp;of minimum wages. Social wealth working its way into workers hands and homes. A revitalized union movement, with attention to climate debt &mdash; ensuring that as more wealth goes into the hands of workers, it comes from bosses and owners, and not from the people of the periphery.&nbsp; The rise of service and care work, and a partial shift to a more knowledge and attention-based economy.&nbsp; Ever larger portions of work in the wealthy West are found in sectors like the university, secondary and primary-school teaching, childcare, and healthcare.&nbsp; Social reproduction.</p>
            <p><strong>Reclassifying </strong>what kinds of labor count. The home-bound and invisible-made work of social reproduction &mdash; cooking, cleaning, raising the future generation, caring for the elder generation &mdash; registered and compensated for in municipal labor registries, where people receive direct welfare payment for their contributions to their societies. Doing this through the budget, the only instrument for collecting human allocation of resources in Western capitalist oligarchies, to ensure that care work receives its every due. Paying labor its due, and this taking place on an international scale &mdash; through building with, rather than at a distance from or over the voices of resistance movements in places like the Philippines and Cuba. The end of suctioning care workers from desiccated neo-colonies like the Philippines, as more people do this work locally and live well, in whatever nations and communities they come from.</p>
            <p>Getting labor on board for the green shift, and showing people how life becomes better while combating imperialism. An overt internationalism, in the form of climate debt payments and respect for southern and peripheral political sovereignty.</p>
            <p>Necessary alliances and social bases forging, for mass-based projects of permanent social change. A front wide enough to enfold petty bourgeois farmers and Black nationalist agriculture workers fighting for food sovereignty. The Red ranchers sewing carbon in soil.&nbsp; The Chicano rural proletariat.&nbsp; The Indigenous groupings fighting for LandBack and against mineral extraction that scores and blights their land.&nbsp; The allies re-localizing manufacturing through fabrication labs and factory takeovers.&nbsp; The endogenous development brigades in Appalachia.&nbsp; The tremendous unpaid social reproductive workers in households, overwhelmingly women.</p>
            <p>At every step, this transition empowering local labor, and remaking development on popular and ecological lines: "development by popular protection," in the words of Adel Samsara. Building autonomy and decentralized power into the transition. &mdash;&nbsp;Not just with any tools, but with specific tools &mdash; ones that foster conviviality so they can be easily used, by anybody, for the accomplishment of a purpose chosen by the user.&nbsp; Every remade trolley and bicycle network, local farm, repair workshop or carpentry site, artisanal cathedral, bicycle, localized city mega-block, internal linkage, even each power plant &mdash; every one that is built, rejiggered, and reworked, increasing our popular and working-class power, and decreasing monopoly rule. "Outer" and "inner" peripheries experiment with endogenous and inward-looking development &mdash; building local capacities and local economies, and safeguarding land from poisoning and people from exploitation.</p>
            <p>Community energy coops in the countryside. Doctors, nurses and common people working together for preventative, soft-footed free healthcare. Forced migrants and refugee communities at the beating heart of Third World solidarity. Autonomous and Leninist formations serving the people. Research clusters and agroeconomic institutions rebuilding the intellectual foundation for responsible landscape management. Ecological populist designers and architects. Artists and artisans working with appropriate local materials. Municipalities grafting cellulosic, carbon dioxide-absorbing greenery onto gray spaces. Village, town, and city level popular referenda for massive investments in public transportation and shifts to biking and walking. Human-scale cities. All of this done with international perspective, and demanding that climate debts be paid and national sovereignty in Third World respected, and settler states decolonized.</p>
            <p>A matter of struggle and choice.</p>
            <p>That starts today.</p>
            </div>

<ShareButton></ShareButton>

    </article>